name: build and test

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run norminette
        uses: alexandregv/norminette-action@v3
        with:
          flags: '.'

      - name: Report result if norminette fails
        if: failure()
        run: echo "Code format is incorrect. Please run norminette on your code."

      - name: Build with make
        run: make

      - name: Verify compilation with Valgrind
        run: valgrind --leak-check=full --show-leak-kinds=all ./minishell exit

      - name: Run tests
        run: ./tests.sh

